### ISSUE TITLE
Command xxx is not found in team XXX?

### ISSUE THREAD

**Issue by maojr** [VeryCB/flask-slack#1]
I am using flask-slack and I did a test with your example(just echo your text).

My Slash Command is /stats
here is my code in server:

``` python
from flask_slack import Slack
from flask import Flask
app = Flask(__name__)

slack = Slack(app)
app.add_url_rule('/', view_func=slack.dispatch)


@slack.command('/stats', token='xxxxxxxxxxxxxxxxxxxx',
               team_id='T0BR3AK3T', methods=['POST'])
def echo_method(**kwargs):
    text = kwargs.get('text')
    return slack.response(text)

if __name__ == "__main__":
    app.run(host='0.0.0.0')                     
```

The URL I put is:(is it okay?)

```
http://server:5000/ 
```

But when I triggered the Slash Command,result

```
Command xxx is not found in team XXX
```

Can you give a  more detailed example?

**Comment by maojr** [comment]
Solved.

``` python
@slack.command('/stats', token='xxxxxxxxxxxxxxxxxxxx',
               team_id='T0BR3AK3T', methods=['POST'])
```

should be

``` python
@slack.command('stats', token='xxxxxxxxxxxxxxxxxxxx',
               team_id='T0BR3AK3T', methods=['POST'])
```

:smile:

**Comment by VeryCB** [comment]
:clap: glad you solved it

**Comment by RoboDonut** [comment]
im running into the same thing running pretty much the same code on pythonanywhere

```
# A very simple Flask Hello World app for you to get started with...
from flask import Flask
from flask_slack import Slack

app = Flask(__name__)
slack = Slack(app)
app.add_url_rule('/', view_func=slack.dispatch)
@slack.command('flaskyou',token=' xxxxxxx',team_id='xxxxxx',methods=['GET'])
def your_method(**kwargs):
    text = kwargs.get('robo says hi from flask on pythonAnywhere 12-8-2015')
    return slack.response(text)
```

**Comment by maojr** [comment]
@RoboDonut 

Maybe your methods should be 'POST'.

```
@slack.command('flaskyou',token=' xxxxxxx',team_id='xxxxxx',methods=['GET'])
```

to:

```
@slack.command('flaskyou',token=' xxxxxxx',team_id='xxxxxx',methods=['POST'])
```

**Comment by VeryCB** [comment]
@RoboDonut Could you paste the error message here?

**Comment by RoboDonut** [comment]
its funny i'm not getting any errors, just the "Command None is not found in team None"

im running my flask app on pythonanywhere.com (you can check out the response here http://robodonut.pythonanywhere.com/ ).

 get -> post doesn't seem to help. when i inspect the command while running the slack client in the browser it seems that the method is always post..

as a note i just updated flask-slack too with out resolution.

im gonna get flask up on a box with outside access and see if the issue is with pythonanywhere. Whats strange is this was working on Sunday night then Monday no worky

**Comment by RoboDonut** [comment]
got this up and running on my server. when i initiate the command this is the response from the server and nothing pops up in slack at all:

```
52.0.190.149 - - [09/Dec/2015 13:59:35] "GET /?token=XXXXXXXX&te
am_id=XXXXXX&team_domain=thespatialones&channel_id=C0A612AS0&channel_name=gen
eral&user_id=U0ACDK98R&user_name=robodonut&command=%2Fflaskyou&text=&response_ur
l=https%3A%2F%2Fhooks.slack.com%2Fcommands%2FT0A61BW1G%2F16318587378%2FbVNknWEso
9ga4MLYthnW5tSQ HTTP/1.1" 200 -
```

**Comment by VeryCB** [comment]
I tried to access `http://robodonut.pythonanywhere.com/?token=XXXXXXXX&team_id=XXXXXX&team_domain=thespatialones&channel_id=C0A612AS0&channel_name=general&user_id=U0ACDK98R&user_name=robodonut&command=%2Fflaskyou&text=` and got `Command flaskyou is not found in team XXXXXX`. The request data is not missing. 

A possible reason could be the command and team_id your registered is different from the parameters in GET request.

**Comment by RoboDonut** [comment]
its strange. If i dump in like basic "hello world" code with the return i get "hello world" back. triple checked team ID and command and token and such. I;m going to be working on this tonight and will document everything and post again
