### ISSUE TITLE
"In Channel" vs "Ephemeral" responses

### ISSUE THREAD

**Issue by RoboDonut** [VeryCB/flask-slack#2]
Hello. 

any chance we can implement in channel and ephemeral responses? shouldn't be to hard  https://api.slack.com/slash-commands

**Comment by VeryCB** [comment]
done by 33a799f0 and released in 0.1.3

**Comment by RoboDonut** [comment]
Awesome!!!

**Comment by RoboDonut** [comment]
Keep getting unexpected keyword arg error. Was it recompiled ? Checked version with pip freeze and it says 0.1.3.

**Comment by RoboDonut** [comment]
When using the response_type in slack.response("message",response_type='in_channel') that is.

**Comment by VeryCB** [comment]
@RoboDonut it's wired. Have you tried to uninstall flask-slack and re-install?

**Comment by RoboDonut** [comment]
I have. Same issue. I was gonna recompile and test in a bit.

**Comment by RoboDonut** [comment]
recompile did no good. i went in and reviewed the source and it does not look like the changes are included with pip  --upgrade

this is what the source .py file looks like on my end after `pip install flask_slack --upgrade`

``` python
 def response(self, text):
        from flask import Response
        return Response(text, content_type='text/plain; charset=utf-8')
```

**Comment by VeryCB** [comment]
@RoboDonut ah...it's my fault, will fix this issue

**Comment by VeryCB** [comment]
@RoboDonut I changed file hierarchy from single file to a python module, without modifying `setup.py`. Now it's fixed by 6852b16 and release in [0.1.5](https://pypi.python.org/pypi/Flask-Slack). Try again?

**Comment by RoboDonut** [comment]
COOL. got it working. many many thanks for the upgrade and your awesome responsiveness.

**Comment by RoboDonut** [comment]
Hey, 

I just wanted to let you know that i put the thing i wrote out to our team today for further testing. so far its been running really well. Thanks for a great library that made this possible. 

In case you were curious the flask app is running on pythonanywhere.com and is tied to a command called /points. It is pretty much a way to give and take points from folks. a host of stats functions too. there are a host of stats function s for retrieving the leader boards and such. 

just thought you might like to know how its being used in the wild.

**Comment by VeryCB** [comment]
@RoboDonut Thanks for your feedback. I'm really happy that this tool is helpful. :smile:
