### ISSUE TITLE
Delayed response

### ISSUE THREAD

**Issue by RoboDonut** [VeryCB/flask-slack#5]
any thoughts on adding the ability to use the delayed response `response_url` ?

https://api.slack.com/slash-commands

**Comment by VeryCB** [comment]
Currently you can access `response_url` from `kwargs`. After doing whatever you need, just send a `POST` request to the `response_url` with `requests`. You can also get a json data with `slack.response()` which could be used as the data to send the request.

**Comment by RoboDonut** [comment]
cool @VeryCB! i'll take a look once pythonanywhere.com's dashboards START WORKING AGAIN!!!
